export const CREATE_SESSION_TOKEN_START = 'CREATE_SESSION_TOKEN_START';
export const CREATE_SESSION_TOKEN_DONE = 'CREATE_SESSION_TOKEN_DONE';
export const CREATE_SESSION_TOKEN_ERROR = 'CREATE_SESSION_TOKEN_ERROR';
export const RESET_SESSION_TOKEN_START = 'RESET_SESSION_TOKEN_START';
export const RESET_SESSION_TOKEN_DONE = 'RESET_SESSION_TOKEN_DONE';
export const RESET_SESSION_TOKEN_ERROR = 'RESET_SESSION_TOKEN_ERROR';
export const CLEAR_SESSION_TOKEN = 'CLEAR_SESSION_TOKEN';
