export const LOAD_QUESTIONS_START = 'LOAD_QUESTIONS_START';
export const LOAD_QUESTIONS_DONE = 'LOAD_QUESTIONS_DONE';
export const LOAD_QUESTIONS_ERROR = 'LOAD_QUESTIONS_ERROR';
export const CLEAR_QUESTIONS = 'CLEAR_QUESTIONS';

export default {
  LOAD_QUESTIONS_START,
  LOAD_QUESTIONS_DONE,
  LOAD_QUESTIONS_ERROR,
  CLEAR_QUESTIONS,
};
